swagger: "2.0"
info:
  version: "2.0"
  title: Experiment server
  description: API for experiments
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: experiment-server2016.herokuapp.com
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: client
    description: Client-related routes
  - name: application
    description: Application-related routes
  - name: configuration-keys
    description: Configurations
  - name: range-constraints
    description: Range-related routes
  - name: exclusion-constrains
    description: Exclusion-related routes
  - name: operators
    description: Operator-related routes
  - name: experiments
    description: Experiment-related routes
    
definitions:

  Application:
    type: object
    allOf:
      - $ref: '#/definitions/NewApplication'
    required:
      - id
    properties:
      id:
        type: integer
      experiments:
        type: array
        items:
          $ref: "#/definitions/Experiment"
      configurationkeys:
        type: array
        items:
          $ref: "#/definitions/ConfigurationKey"

  NewApplication:
    type: object
    required:
      - name
    properties:
      name:
        type: string

  ConfigurationKey:
    type: object
    allOf:
      - $ref: '#/definitions/NewConfigurationKey'
    required:
      - id
    properties:
      id:
        type: integer
      rangeconstraints:
        type: array
        items:
          $ref: "#/definitions/RangeConstraint"

  NewConfigurationKey:
    type: object
    required:
      - name
      - type
      - application_id
    properties:
      name:
        type: string
      type:
        type: string
      application_id:
        type: integer

  Configuration:
    type: object
    required:
      - id
      - experimentgroup_id
      - key
      - value
    properties:
      id:
        type: integer
      experimentgroup_id:
        type: integer
      key:
        type: string
      value:
        type:
          - integer
          - string
          - boolean

  DataItem:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
      user_id:
        type: integer
      key:
        type: string
      value:
        type:
          - integer
          - string
          - boolean
      startDateTime:
        type: string
      endDateTime:
        type: string

  ExclusionConstraint:
    type: object
    required:
      - id
      - first_configurationkey_id
      - first_operator_id
      - first_value_a
      - first_value_b
      - second_configurationkey_id
      - second_operator_id
      - second_value_a
      - second_value_b
    properties:
      id:
        type: integer
      first_configurationkey_id:
        type: integer
      first_operator_id:
        type: integer
      first_value_a:
        type:
          - string
        x-nullable: true
      first_value_b:
        type:
          - string
        x-nullable: true
      second_configurationkey_id:
        type: integer
      second_operator_id:
        type:
          - integer
        x-nullable: true
      second_value_a:
        type:
          - string
        x-nullable: true
      second_value_b:
        type:
          - string
        x-nullable: true
        
  NewExclusionConstraint:
    type: object
    required:
      - first_configurationkey_id
      - first_operator_id
      - first_value_a
      - first_value_b
      - second_configurationkey_id
      - second_operator_id
      - second_value_a
      - second_value_b
    properties:
      first_configurationkey_id:
        type: integer
      first_operator_id:
        type: integer
      first_value_a:
        type: string
        x-nullable: true
      first_value_b:
        type: string
        x-nullable: true
      second_configurationkey_id:
        type: integer
      second_operator_id:
        type: integer
        x-nullable: true
      second_value_a:
        type: string
        x-nullable: true
      second_value_b:
        type: string
        x-nullable: true

  ExperimentGroup:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
      experiment_id:
        type: integer
      name:
        type: string
      configurations:
        type: array
        items:
          $ref: "#/definitions/Configuration"
      users:
        type: array
        items:
          $ref: "#/definitions/User"


  Experiment:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
      application_id:
        type: integer
      name:
        type: string
      startDatetime:
        type: string
        format: date-time
      endDatetime:
        type: string
        format: date-time
      experimentgroups:
        type: array
        items:
          $ref: "#/definitions/ExperimentGroup"
      size:
        type: integer

  NewExperiment:
    type: object
    required:
      - name
      - application_id
      - startDatetime
      - endDatetime
      - size
    properties:
      application_id:
        type: integer
      name:
        type: string
      startDatetime:
        type: string
        format: date-time
      endDatetime:
        type: string
        format: date-time
      size:
        type: integer

  Operator:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
      math_value:
        type: string
      human_value:
        type: string
      rangeconstraints:
        type: array
        items:
          $ref: "#/definitions/RangeConstraint"

  RangeConstraint:
    type: object
    allOf:
      - $ref: '#/definitions/NewRangeConstraint'
    required:
      - id
    properties:
      id:
        type: integer

  NewRangeConstraint:
    type: object
    required:
      - value
    properties:
      configurationkey_id:
        type: integer
      operator_id:
        type: integer
      value:
        type: string

  Client:
    type: object
    allOf:
      - $ref: '#/definitions/Client'
    required:
       - id
    properties:
        id:
          type: integer
        dataitems:
          type: array
          items:
            $ref: "#/definitions/DataItem"
        experimentgroups:
          type: array
          items:
            $ref: "#/definitions/ExperimentGroup"

  Client:
    type: object
    required:
      - username
    properties:
      username:
        type: string
